jupyterhub:
#  proxy:
#    secretToken: {{ cat (.Release.Time | toString) .Release.Name .Chart.Name | sha256sum | substr 0 31 }}
  singleuser:
    memory:
      limit: 1G
      guarantee: 1G
    cpu:
      limit: 0.5
      gaurantee: 0.5
    image:
      name: jupyter/datascience-notebook
      tag: basic
    defaultUrl: "/lab"
    profileList:
      - display_name: "DataScience Notebook"
        description: "Python, Julia, R Notebooks."
        default: true
      - display_name: "Original Hub Interface"
        description: "Same as DataScience Notebook, but the traditional JupyterHub interface."
        kubespawner_override:
          default_url: "/tree"
  hub:
    extraConfig: 
      jupyterlab: |
        c.Spawner.cmd = ['jupyter-labhub']

