name: ds-jupyterlab
version: 0.1.1
appVersion: 0.9
description: JupyerLab with Python, Julia, R Support (no RStudio)
icon: https://gist.githubusercontent.com/oneilsh/7c0afdbcb370790d8558468ee73b4eb7/raw/802a701d6c4503ca5d44d417b1bc903712546bb8/jupyterlab.svg
keywords:
- lab
- python
- R
- julia
home: https://github.com/oneilsh/charts-repo
sources:
  - https://github.com/oneilsh/charts-repo
maintainers:
- name: Shawn
  email: oneilsh@gmail.com
engine: gotpl
