jupyterhub:
  proxy:
    secretToken: "78767972dd3d0db5a98fb56554f4484daa57bc35bd73dc61aafebed8ac9fe3df"
  singleuser:
    memory:
      limit: 1G
      guarantee: 0.5G
    cpu:
      limit: 0.5
      gaurantee: 1.0
    image:
      name: jupyter/datascience-notebook
      tag: 82d1d0bf0867
    defaultUrl: "/lab"
    extraEnv:
      #NB_USER: "{username}"
      CHOWN_HOME: "yes"
      CHOWN_EXTRA_OPTS: '-R'
    uid: 0
    fsGid: 0
    cmd: ['start-singleuser.sh']

    #profileList:
    #  - display_name: "DataScience Notebook"
    #    description: "Python, Julia, R Notebooks."
    #    default: true
    #  - display_name: "Original Hub Interface"
    #    description: "Same as DataScience Notebook, but the traditional JupyterHub interface."
    #    kubespawner_override:
    #      default_url: "/tree"
    
    storage:
      type: "static"
      static:
        pvcName: "nfs-claim-home"
        subPath: "home/{username}"
      homeMountPath: /home/{username}
      # extraVolumes: 
      #   - name: jupyterhub-shared
      #     persistentVolumeClaim:
      #       claimName: shared-vol
      # extraVolumeMounts:
      #   - name: jupyterhub-shared
      #     mountPath: /home/shared


  ingress:
    enabled: true
    hosts:
      - ae0ddea81dfc711e9bc930243f4b71e9-1085611928.us-west-2.elb.amazonaws.com
        #pathSuffix: '*'
    annotations: 
      kubernetes.io/ingress.class: nginx

  hub:
    baseUrl: /oneils/jupyter_test/
    extraConfig:
      authsetting: |
        from jupyterhub.auth import DummyAuthenticator
        from tornado import gen

        class DummyExtraAuthenticator(DummyAuthenticator):
          
          @gen.coroutine
          def pre_spawn_start(self, user, spawner):
            spawner.environment['NB_USER'] = user.name
        
        c.JupyterHub.authenticator_class = DummyExtraAuthenticator


#nfs-server-provisioner:
#  #persistence: 
#  #  enabled: true
#  #  storageClass: "gp2"
#  #  accessMode: ReadWriteOnce
#  #  size: 20Gi
#
#  storageClass:
#    create: true
#    defaultClass: false
#    name: nfs
#    allowVolumeExpansion: true
#    provisionerName: nfs-prov
#    mountOptions:
#      - vers=4.1
#      - noatime
#
#  # otherwise the name might be too long and hit the 63-char limit
#  nameOverride: nfs-prov
#  fullnameOverride: nfs-prov
