kind: Secret
apiVersion: v1
metadata:
  name: hub-secret
  labels:
    {{- include "jupyterhub.labels" . | nindent 4 }}
type: Opaque
data:
  proxy.token: {{ cat (.Release.Time | toString) .Release.Name .Chart.Name | sha1sum | substr 0 32 | b64enc | quote }}
