jupyterhub:
  proxy:
    secretToken: "78767972dd3d0db5a98fb56554f4484daa57bc35bd73dc61aafebed8ac9fe3df"
  singleuser:
    memory:
      limit: 1G
      guarantee: 1G
    cpu:
      limit: 0.5
      gaurantee: 0.5
    image:
      name: jupyter/datascience-notebook
      tag: 82d1d0bf0867
    defaultUrl: "/lab"

    #profileList:
    #  - display_name: "DataScience Notebook"
    #    description: "Python, Julia, R Notebooks."
    #    default: true
    #  - display_name: "Original Hub Interface"
    #    description: "Same as DataScience Notebook, but the traditional JupyterHub interface."
    #    kubespawner_override:
    #      default_url: "/tree"

  hub:
    extraConfig: 
      jupyterlab: |
        c.Spawner.cmd = ['jupyter-labhub']
      authsetting: |
        class DummyExtraAuthenticator(DummyAuthenticator):
          @gen.coroutine
        def pre_spawn_start(self, user, spawner):
          spawner.environment['NB_USER'] = user.name





