apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: shared-vol
  # trying to avoid this apparent bug: https://stackoverflow.com/questions/51358856/kubernetes-cant-delete-persistentvolumeclaim-pvc
  finalizers: []
spec:
  storageClassName: nfs
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 2Gi
