apiVersion: v1
kind: PersistentVolume
metadata:
  name: home-pv
  labels:
    usage: home
spec:
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteMany
  nfs:
    server: nfs-service.ds-jupyterhub.svc.cluster.local
    path: "/"

