apiVersion: v1
kind: PersistentVolume
metadata:
  name: home-pv
spec:
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteMany
  nfs:
    server: nfs-claim-home-nfs-server-provisioner
    path: "/"

