#apiVersion: v1
#kind: PersistentVolumeClaim
#apiVersion: v1
#metadata:
#  name: efs-persist
#spec:
#  storageClassName: ""
#  accessModes:
#    - ReadWriteMany
#  resources:
#    requests:
#      storage: 11Gi

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: nfs-claim-home 
  # trying to avoid this apparent bug: https://stackoverflow.com/questions/51358856/kubernetes-cant-delete-persistentvolumeclaim-pvc
  #finalizers: []
spec:
  #storageClassName: nfs
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 10Gi
