kind: Pod
apiVersion: v1
metadata:
  name: nfs-server-pod
  labels:
    role: nfs
spec:
  volumes: 
    - name: nfsexport
      persistentVolumeClaim:
        claimName: nfs-pvc
  containers:
    - name: nfs-server-container
      image: cpuguy83/nfs-server
      securityContext:
        privileged: true
      args:
        # Pass the paths to share to the Docker image
        - /exports
      volumeMounts:
        - name: nfsexport
          mountPath: /exports
  
